### ISSUE TITLE
OGBG Pytorch workload returns Cuda NCCL Runtime error

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#113]
The OGBG Pytorch workload returns an 'unhandled system error' from CUDA NCCL during training. 

## Description
Traceback: 
```
I0810 17:25:55.830966 139956716267328 submission_runner.py:296] --- Tuning run 1/1 ---
I0810 17:25:55.831372 139956716267328 submission_runner.py:173] Initializing dataset.
I0810 17:25:55.831465 139956716267328 submission_runner.py:180] Initializing model.
I0810 17:25:57.511094 139956716267328 submission_runner.py:183] Initializing optimizer.
I0810 17:25:57.511782 139956716267328 submission_runner.py:201] Starting training loop.
I0810 17:25:57.565685 139956716267328 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0810 17:25:58.602069 139956716267328 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0810 17:25:59.788436 139956716267328 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
I0810 17:25:59.790120 139956716267328 dataset_builder.py:351] Reusing dataset ogbg_molpcba (/home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2)
I0810 17:25:59.790260 139956716267328 logging_logger.py:36] Constructing tf.data.Dataset ogbg_molpcba for split train, from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
Traceback (most recent call last):
  File "submission_runner.py", line 381, in <module>
    app.run(main)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 369, in main
    FLAGS.num_tuning_trials)
  File "submission_runner.py", line 301, in score_submission_on_workload
    hyperparameters, rng, profiler)
  File "submission_runner.py", line 227, in train_once
    rng=update_rng)
  File "/home/kasimbeg_google_com/algorithmic-efficiency/reference_submissions/ogbg/ogbg_pytorch/submission.py", line 67, in update_params
    loss.backward()
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 34, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 45, in forward
    return comm.reduce_add_coalesced(grads_, destination)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/comm.py", line 143, in reduce_add_coalesced
    flat_result = reduce_add(flat_tensors, destination)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/nn/parallel/comm.py", line 96, in reduce_add
    nccl.reduce(inputs, output=result, root=root_index)
  File "/home/kasimbeg_google_com/env/lib/python3.7/site-packages/torch/cuda/nccl.py", line 93, in reduce
    torch._C._nccl_reduce(inputs, _output, root, op, streams, comms)
RuntimeError: NCCL Error 2: unhandled system error
```

*Provide more details on the bug itself*

## Steps to Reproduce
On tf-agents/init-to-winit which has 8 V100 machines run:

```
python3 submission_runner.py --framework=pytorch --workload=ogbg --submission_path=reference_submissions/ogbg/ogbg_pytorch/submission.py --tuning_search_space=reference_submissions/ogbg/tuning_search_space.json --num_tuning_trials=1
```

## Source or Possible Fix
Not clear what the possible fix is at the moment. 
Note: I previously ran the above command from a bash script, and the error was not returned to the console. Instead it just looked like the run was hanging.

**Comment by priyakasimbeg** [comment]
Note this Runtime Error is no longer happening on the up-to-date main branch. Getting the following message in the logs: 

```
I0810 18:36:41.094143 140719074539328 submission_runner.py:306] --- Tuning run 1/1 ---
I0810 18:36:41.094606 140719074539328 submission_runner.py:175] Initializing dataset.
I0810 18:36:41.094711 140719074539328 submission_runner.py:182] Initializing model.
I0810 18:36:42.775108 140719074539328 submission_runner.py:185] Initializing optimizer.
I0810 18:36:42.775791 140719074539328 submission_runner.py:203] Starting training loop.
I0810 18:36:42.829380 140719074539328 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I0810 18:36:43.859815 140719074539328 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0810 18:36:44.912751 140719074539328 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
I0810 18:36:44.914345 140719074539328 dataset_builder.py:351] Reusing dataset ogbg_molpcba (/home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2)
I0810 18:36:44.914499 140719074539328 logging_logger.py:36] Constructing tf.data.Dataset ogbg_molpcba for split train, from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
I0810 18:37:03.434461 140719074539328 spec.py:248] Evaluating on the training split.
I0810 18:37:03.437883 140719074539328 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
I0810 18:37:03.439840 140719074539328 dataset_builder.py:351] Reusing dataset ogbg_molpcba (/home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2)
I0810 18:37:03.439985 140719074539328 logging_logger.py:36] Constructing tf.data.Dataset ogbg_molpcba for split train[:10000], from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
W0810 18:37:04.847843 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:37:05.844585 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:37:06.746172 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:37:07.572035 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:37:08.336251 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
I0810 18:37:58.608500 140719074539328 spec.py:259] Evaluating on the validation split.
I0810 18:37:58.610959 140719074539328 dataset_info.py:358] Load dataset info from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
I0810 18:37:58.612793 140719074539328 dataset_builder.py:351] Reusing dataset ogbg_molpcba (/home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2)
I0810 18:37:58.612933 140719074539328 logging_logger.py:36] Constructing tf.data.Dataset ogbg_molpcba for split validation, from /home/kasimbeg_google_com/tensorflow_datasets/ogbg_molpcba/0.1.2
W0810 18:37:59.524865 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:00.323966 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:01.118193 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:01.920755 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:02.706216 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:03.497344 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:04.303926 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:05.098161 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:05.890193 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:06.708162 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:07.509344 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
W0810 18:38:08.306322 140719074539328 metrics.py:235] Ignoring mask for model output 'loss' because of shape mismatch: output.shape=() vs. mask.shape=(2056, 128)
```

@runame, is that expected?

**Comment by runame** [comment]
Yes, this is expected. I'm closing this issue for now, feel free to reopen it if there are still problems or questions remaining.
