### ISSUE TITLE
fastmri not initally working with pytorch

### ISSUE THREAD

**Issue by rakshithvasudev** [mlcommons/algorithmic-efficiency#138]
Couldn't debug much here just wanted to report the output of the run.

```
I0921 22:25:00.183000 140737350199104 submission_runner.py:359] --- Tuning run 1/1 ---
I0921 22:25:00.183330 140737350199104 submission_runner.py:198] Initializing dataset.
I0921 22:25:00.183405 140737350199104 submission_runner.py:205] Initializing model.
I0921 22:25:04.090010 140737350199104 submission_runner.py:208] Initializing optimizer.
I0921 22:25:04.090586 140737350199104 submission_runner.py:220] Initializing metrics bundle.
I0921 22:25:04.090652 140737350199104 submission_runner.py:236] Starting training loop.
I0921 22:25:51.947953 140737350199104 spec.py:257] Evaluating on the training split.
Traceback (most recent call last):
  File "submission_runner.py", line 450, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 429, in main
    score = score_submission_on_workload(workload,
  File "submission_runner.py", line 361, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 286, in train_once
    latest_eval_result = workload.eval_model(global_batch_size,
  File "/work/algorithmic_efficiency/spec.py", line 258, in eval_model
    train_metrics = self._eval_model_on_split(
  File "/work/algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py", line 269, in _eval_model_on_split
    batch = next(self._eval_iters[split])
  File "/work/algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py", line 100, in build_input_queue
    for batch in it:
  File "/work/algorithmic_efficiency/data_utils.py", line 36, in cycle
    batch = next(iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1251, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 463, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
    init_fn(worker_id)
  File "/work/algorithmic_efficiency/workloads/fastmri/fastmri_pytorch/workload.py", line 71, in worker_init_fn
    if data.transform.mask_func is not None:
AttributeError: 'Subset' object has no attribute 'transform'
```

*Provide more details on the bug itself*

AttributeError: 'Subset' object has no attribute 'transform'

*An ordered list of steps to recreating the issue*

`torchrun --no_python  --nproc_per_node 8 bash -c  "python3 submission_runner.py --workload=fastmri --framework=pytorch --submission_path=reference_submissions/fastmri/fastmri_pytorch/submission.py --tuning_search_space=reference_submissions/fastmri/tuning_search_space.json --num_tuning_trials=1 --data_dir=/dataset"`

**Comment by runame** [comment]
I have fixed this, but will be irrelevant after unifying the input pipelines anyway. Leaving this issue open until the corresponding PR (WIP) is merged.
