### ISSUE TITLE
imagenet pytorch workloads break during eval on test set

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#186]
imagenet pytorch ViT and Resnet workloads break during eval on imagenet_v2 test split.

## Description
Traceback:
```
I1013 18:53:17.879712 140653770622784 submission_runner.py:243] Initializing metrics bundle.
I1013 18:53:17.879878 140653770622784 submission_runner.py:257] Starting training loop.
I1013 18:53:47.672241 140653770622784 spec.py:288] Evaluating on the training split.
I1013 18:55:05.126325 140653770622784 spec.py:300] Evaluating on the validation split.
I1013 18:56:16.793108 140653770622784 spec.py:315] Evaluating on the test split.
I1013 18:56:16.796242 140653770622784 dataset_info.py:358] Load dataset info from /home/kasimbeg/imagenet_v2/matched-frequency/3.0.0
I1013 18:56:16.798682 140653770622784 dataset_builder.py:351] Reusing dataset imagenet_v2 (/home/kasimbeg/imagenet_v2/matched-frequency/3.0.0)
I1013 18:56:16.798848 140653770622784 logging_logger.py:36] Constructing tf.data.Dataset imagenet_v2 for split test, from /home/kasimbeg/imagenet_v2/matched-frequency/3.0.0
Traceback (most recent call last):
  File "submission_runner.py", line 495, in <module>
    app.run(main)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 479, in main
    FLAGS.tokenizer_vocab_path)
  File "submission_runner.py", line 411, in score_submission_on_workload
    tokenizer_vocab_path)
  File "submission_runner.py", line 307, in train_once
    global_step)
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 324, in eval_model
    global_step=global_step)
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py", line 249, in _eval_model_on_split
    batch = next(self._eval_iters[split])
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py", line 39, in imagenet_v2_to_torch
    new_v = np.transpose(new_v, (0, 3, 1, 2))
  File "<__array_function__ internals>", line 6, in transpose
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 660, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

## Steps to Reproduce
These commands both result in the above error:
```
python submission_runner.py     --framework=pytorch     --data_dir=~/local_data/imagenet/pytorch     --imagenet_v2_data_dir=~     --experiment_dir=~     --experiment_name=target_setting     --workload=imagenet_resnet     --submission_path=target_setting_runs/pytorch_nesterov.py     --tuning_search_space=target_setting_runs/imagenet_resnet/tuning_search_space.json
```

```
python submission_runner.py     --framework=pytorch     --data_dir=~/local_data/imagenet/pytorch     --imagenet_v2_data_dir=~     --experiment_dir=~     --experiment_name=target_setting     --workload=imagenet_vit     --submission_path=target_setting_runs/pytorch_nadamw.py     --tuning_search_space=target_setting_runs/imagenet_vit/tuning_search_space.json
```

## Source or Possible Fix
I think something is off in the input pipeline for imagenet_v2. Strangely enough though running with torchrun does not raise this error; the following command does not return an error:
```
 torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py     --framework=pytorch     --data_dir=~/local_data/imagenet/pytorch     --imagenet_v2_data_dir=~     --experiment_dir=~     --experiment_name=target_setting     --workload=imagenet_vit     --submission_path=target_setting_runs/pytorch_nadamw.py     --tuning_search_space=target_setting_runs/imagenet_vit/tuning_search_space.json 
 ```

**Comment by priyakasimbeg** [comment]
I think the issue is in this method:

```
def imagenet_v2_to_torch(batch):
  # Slice off the part of the batch for this device and then transpose from
  # [N, H, W, C] to [N, C, H, W]. Only transfer the inputs to GPU.
  new_batch = {}
  for k, v in batch.items():
    new_v = v[RANK]
    if k == 'inputs':
      new_v = np.transpose(new_v, (0, 3, 1, 2))
    dtype = torch.long if k == 'targets' else torch.float
    new_batch[k] = torch.as_tensor(new_v, dtype=dtype, device=DEVICE)
  return new_batch
```
if `USE_PYTORCH_DDP` is False than `v` will not have the extra dimension for device so `new_v = v[RANK]` is a bug in that case. Will submit a after verifying.
