### ISSUE TITLE
ogbg returns NaN error 

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#198]
The ogbg jax workload returned `ValueError: Input contains NaN, infinity or a value too large for dtype('float32')` after about 72 steps. 
                                                                                          
## Description
Traceback:
```
I1018 21:44:36.960185 140585414121280 checkpoints.py:356] Saving checkpoint at step: 72                                                                                            
I1018 21:44:37.026029 140585414121280 checkpoints.py:317] Saved checkpoint at /home/kasimbeg/target_setting/ogbg_jax/trial_1/checkpoint_72                                         
I1018 21:44:37.026265 140585414121280 checkpoints.py:344] Removing checkpoint at /home/kasimbeg/target_setting/ogbg_jax/trial_1/checkpoint_2                                       
I1018 21:44:37.029724 140585414121280 checkpoint_utils.py:163] Saved checkpoint to /home/kasimbeg/target_setting/ogbg_jax/trial_1/checkpoint_72                                    
I1018 21:46:39.350129 140585414121280 spec.py:288] Evaluating on the training split.                                                                                               
Traceback (most recent call last):                                                                                                                                                 
  File "submission_runner.py", line 545, in <module>                                                                                                                               
    app.run(main)                                                                                                                                                                  
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                       
    _run_main(main, args)                                                                                                                                                          
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                 
    sys.exit(main(argv))                                                                                                                                                           
  File "submission_runner.py", line 529, in main                                                                                                                                   
    FLAGS.tokenizer_vocab_path)                                                                                                                                                    
  File "submission_runner.py", line 463, in score_submission_on_workload                                                                                                           
    tokenizer_vocab_path)                                                                                                                                                          
  File "submission_runner.py", line 323, in train_once                                                                                                                             
    global_step)                                                                                                                                                                   
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 297, in eval_model                                                                             
    global_step=global_step)                                                                                                                                                       
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/ogbg/workload.py", line 138, in _eval_model_on_split                                                
    return {k: float(v) for k, v in total_metrics.compute().items()}                                                                                                               
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/clu/metrics.py", line 513, in compute                                                                
    for metric_name, metric in vars(self).items()                                                                                                                                  
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/clu/metrics.py", line 514, in <dictcomp>                                                             
    if metric_name != "_reduction_counter" 
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/ogbg/metrics.py", line 65, in compute                                                               
    labels[is_labeled, task], probs[is_labeled, task])
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 233, in average_precision_score
    average_precision, y_true, y_score, average, sample_weight=sample_weight
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 206, in _binary_uninterpolated_average_precision
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 859, in precision_recall_curve
    y_true, probas_pred, pos_label=pos_label, sample_weight=sample_weight
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 737, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 134, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

## Steps to Reproduce

On kasimbeg-1 vm on main branch run:
```
python3 submission_runner.py \
    --framework=jax \
    --data_dir=/home/kasimbeg/tensorflow_datasets \
    --experiment_dir=/home/kasimbeg \
    --experiment_name=target_setting \
    --workload=ogbg \
    --submission_path=reference_algorithms/target_setting_algorithms/jax_nesterov.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/ogbg/tuning_search_space.json
```

## Source or Possible Fix
From the traceback it looks like the NaN is in the metrics computation but it is possible and likely that the NaN may have come from the update step.

**Comment by priyakasimbeg** [comment]
Also happens on pytorch workload.
Traceback:

```
ValueError  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/clu/metrics.py", line 514, in <dictcomp>
: Input contains NaN, infinity or a value too large for dtype('float32').
    assert_all_finite(y_score)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 134, in assert_all_finite
    for metric_name, metric in vars(self).items()
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/clu/metrics.py", line 514, in <dictcomp>
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    if metric_name != "_reduction_counter"
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/ogbg/metrics.py", line 65, in compute
    labels[is_labeled, task], probs[is_labeled, task])
      File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 233, in average_precision_score
    type_err, msg_dtype if msg_dtype is not None else X.dtypeif metric_name != "_reduction_counter"
    ```

**Comment by priyakasimbeg** [comment]
Reran with the `jax_debug_nans` flag and the error is somewhere in update_params... Unfortunately the traceback doesn't say exactly where.

```
Traceback (most recent call last):
  File "submission_runner.py", line 542, in <module>
    app.run(main)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 526, in main
    FLAGS.tokenizer_vocab_path)
  File "submission_runner.py", line 461, in score_submission_on_workload
    tokenizer_vocab_path)
  File "submission_runner.py", line 301, in train_once
    rng=update_rng)
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/jax_submission_base.py", line 97, in update_params
    label_smoothing)
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/jax/_src/api.py", line 145, in _nan_check_posthook
    fun._cache_miss(*args, **kwargs)[0]  # probably won't return
FloatingPointError: invalid value (nan) encountered in parallel computation
```

**Comment by runame** [comment]
Do you get the same error when running the development algorithm for OGBG?

**Comment by runame** [comment]
I could reproduce the error for the target setting algorithm. I'm currently running the development algorithm and it didn't run into the same issue yet, it's at 1986 steps right now.

**Comment by runame** [comment]
Update: it ran without issues, but I stopped it since it doesn't fully converge to the target, as the hyperparameters are not chosen for the batch size.

**Comment by priyakasimbeg** [comment]
The issue seems to be in the loss calculation. Testing with the following diff: 
```
@@ -40,12 +40,12 @@ def pmapped_train_step(workload,
         dropout_rate=None,
         aux_dropout_rate=None,
         update_batch_norm=True)
-    loss = jnp.mean(
-        workload.loss_fn(
+    per_example_losses = workload.loss_fn(
             label_batch=batch['targets'],
             logits_batch=logits,
             mask_batch=batch.get('weights'),
-            label_smoothing=label_smoothing))
+            label_smoothing=label_smoothing)
+    loss = jnp.sum(jnp.where(batch['weights'], per_example_losses, 0)) / jnp.sum(batch['weights'])
     return loss, new_model_state
```

**Comment by priyakasimbeg** [comment]
Update on the test run above, the run hit the target mAP in 33K steps.
```
 (33503, {'train/accuracy': 0.991937518119812, 'train/loss': 0.026281997561454773, 'train/mean_average_precision': 0.4982242845366346, 'validation/accuracy': 0.987113356590271, 'validation/loss': 0.04380372539162636, 'validation/mean_average_precision': 0.2843051966905668, 'validation/num_examples': 43793, 'test/accuracy': 0.986303985118866, 'test/loss': 0.0465334951877594, 'test/mean_average_precision': 0.2714221630755831, 'test/num_examples': 43793, 'global_step': 33503, 'preemption_count': 0})], 'global_step': 33503}
I1025 05:45:25.208798 140310246479680 submission_runner.py:484] Timing: 6715.153635025024
```

Will add a clean fix for both jax and pytorch and rerun.
