### ISSUE TITLE
wmt pytorch device indexing error 

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#201]
The wmt pytorch workload breaks with an IndexError when trying to set the device. 

## Description
Traceback 
```
W1019 05:02:37.751141 140375856039744 xla_bridge.py:352] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)                              
Traceback (most recent call last):                                                                                                                                                 
  File "submission_runner.py", line 498, in <module>                                                                                                                               
    app.run(main)                                                                                                                                                                  
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                       
    _run_main(main, args)                                                                                                                                                          
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                 
    sys.exit(main(argv))                                                                                                                                                           
  File "submission_runner.py", line 456, in main                                                                                                                                   
    workload_class_name=workload_metadata['workload_class_name'])                                                                                                                  
  File "submission_runner.py", line 171, in import_workload                                                                                                                        
    workload_module = importlib.import_module(workload_path)                                                                                                                       
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module                                                                                                
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                    
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                                  
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                                
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                                                                                       
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                                                                                
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                                                                          
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                                     
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 18, in <module>                                                  
    from algorithmic_efficiency.workloads.wmt import decode                                                                                                                        
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/decode.py", line 20, in <module>                                                                
    DEVICE = jax.devices()[RANK] 
```

Ran command
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py \
    --framework=pytorch \
    --data_dir=\home\kasimbeg/tensorflow_datasets \
    --experiment_dir=\home\kasimbeg \
    --experiment_name=target_setting \
    --workload=wmt \
    --submission_path=reference_algorithms/target_setting_algorithms/pytorch_adamw.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/wmt/tuning_search_space.json 
```

## Source or Possible Fix
It looks like jax cannot find the GPU. Probably because I have not installed the jax gpu versions to run the python workloads. I have:
```
jax==0.3.16
jaxlib==0.3.15
```
So we should probably get the devices differently.

**Comment by priyakasimbeg** [comment]
In the other pytorch workloads DEVICE is set like this:
```
USE_PYTORCH_DDP, RANK, DEVICE, N_GPUS = pytorch_utils.pytorch_setup()
```

**Comment by priyakasimbeg** [comment]
Looks like this was already fixed in https://github.com/mlcommons/algorithmic-efficiency/pull/190.
