### ISSUE TITLE
imagenet vit pytorch NCCL Time out error

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#203]
The imagenet pytorch target setting run returned an NCCL time out error after a 258K steps. 

## Description
The target setting run was expected to reach the target around 140K steps, so admittedly 258K steps way past what we ideally want. As an aside, I believe there are open diffs (like the data augmentation) between the reference runs and target setting runs that still need to be reconciled before we can expect to reach the target in a similar number of steps.

In any case @znado noticed a similar error in the fastmri pytorch workload, so I thought this imagenet error is worth logging here.
Traceback:
```
I1016 03:55:12.044501 140450552076096 spec.py:288] Evaluating on the training split.
I1016 03:55:24.830125 140450552076096 spec.py:300] Evaluating on the validation split.
I1016 03:55:38.262476 140450552076096 spec.py:315] Evaluating on the test split.
I1016 03:55:39.542862 140450552076096 submission_runner.py:314] 119769.04s      259048  {'train/accuracy': 0.2681, 'train/loss': 3.863645, 'validation/accuracy': 0.16694, 'validation/loss': 4.4891546875, 'test/accuracy': 0.0012, 'test/loss': 8.1409953125}
I1016 03:55:39.566237 140413461686016 logging_writer.py:48] [259048] global_step=259048, test/accuracy=0.001200, test/loss=8.140995, train/accuracy=0.268100, train/loss=3.863645, validation/accuracy=0.166940, validation/loss=4.489155
[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3890145, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800256 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3890145, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800383 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:414] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3890145, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1800383 milliseconds before timing out.
Fatal Python error: Aborted
```

## Steps to Reproduce
On kasimbeg-6
Run:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py \
    --framework=pytorch \
    --data_dir=~/local_data/imagenet/pytorch \
    --imagenet_v2_data_dir=~ \
    --experiment_dir=~ \
    --experiment_name=target_setting \
    --workload=imagenet_vit \
    --submission_path=reference_algorithms/target_setting_algorithms/pytorch_nadamw.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/imagenet_vit/tuning_search_space.json 
```

**Comment by priyakasimbeg** [comment]
I reran it on the most up to date main branch and got a different error.,  I think related to the DDP data pipeline:
```
I1021 19:37:35.390425 140406761183040 submission_runner.py:212] Initializing model.                                                                                                
I1021 19:37:37.514532 140406761183040 submission_runner.py:215] Initializing optimizer.                                                                                            
I1021 19:37:37.515632 140406761183040 submission_runner.py:222] Initializing metrics bundle.                                                                                       
I1021 19:37:37.515718 140406761183040 submission_runner.py:239] Initializing checkpoint and logger.                                                                                
I1021 19:37:38.145177 140406761183040 submission_runner.py:260] Saving meta data to /home/kasimbeg/target_setting/imagenet_vit_pytorch/trial_1/meta_data_0.json                    
I1021 19:37:38.146010 140406761183040 submission_runner.py:263] Saving flags to /home/kasimbeg/target_setting/imagenet_vit_pytorch/trial_1/flags_0.json                            
I1021 19:37:38.171624 140406761183040 submission_runner.py:269] Starting training loop.                                                                                            
Traceback (most recent call last):                                                                                                                                                 
  File "submission_runner.py", line 547, in <module>                                                                                                                               
    app.run(main)                                                                                                                                                                  
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                       
    _run_main(main, args)                                                                                                                                                          
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                 
    sys.exit(main(argv))                                                                                                                                                           
  File "submission_runner.py", line 531, in main                                                                                                                                   
    FLAGS.tokenizer_vocab_path)                                                                                                                                                    
  File "submission_runner.py", line 466, in score_submission_on_workload                                                                                                           
    tokenizer_vocab_path)                                                                                                                                                          
  File "submission_runner.py", line 299, in train_once                                                                                                                             
    rng=update_rng)                                                                                                                                                                
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/pytorch_submission_base.py", line 57, in update_params                                
    torch.nn.utils.clip_grad_norm_(current_model, grad_clip)                                                                                                                       
  File "/home/kasimbeg/algorithmic-efficiency/env/lib/python3.7/site-packages/torch/nn/utils/clip_grad.py", line 32, in clip_grad_norm_                                            
    parameters = [p for p in parameters if p.grad is not None]                                                                                                                     
TypeError: 'DistributedDataParallel' object is not iterable
```
@runame does running the above command also give you this error?

**Comment by pomonam** [comment]
This is my fault introduced in #193. I will submit a PR soon.

**Comment by priyakasimbeg** [comment]
Thanks for fixing this! I will rerun the imagenet ViT on latest main branch now.

**Comment by priyakasimbeg** [comment]
Verified that this is fixed.
