### ISSUE TITLE
Criteo OOM at batch size 524k

### ISSUE THREAD

**Issue by znado** [mlcommons/algorithmic-efficiency#217]
I'm investigating, my current suspicion is that it has to do with some dtypes. I also had to make a few fixes https://github.com/mlcommons/algorithmic-efficiency/pull/218 with increasing the model size to match the target setting runs, and fixing some loss fn shapes again.

Jax stacktrace:
```
(env) znado@znado-2:~/algorithmic-efficiency$ python3 submission_runner.py     --framework=jax     --data_dir=/home/znado/criteo_parts     --experiment_dir=/home/znado     --experiment_name=dev_algo     --workload=criteo1tb     --submission_path=reference_algorithms/development_algorithms/criteo1tb/criteo1tb_jax/submission.py     --tuning_search_space=reference_algorithms/development_algorithms/criteo1tb/tuning_search_space.json
WARNING:absl:GlobalAsyncCheckpointManager is not imported correctly. Checkpointing of GlobalDeviceArrays will not be available.To use the feature, install tensorstore.
ERROR:root:Unable to import wandb.
Traceback (most recent call last):
  File "/home/znado/algorithmic-efficiency/algorithmic_efficiency/logger_utils.py", line 22, in <module>
    import wandb  # pylint: disable=g-import-not-at-top
ModuleNotFoundError: No module named 'wandb'
I1021 20:53:42.732529 140139075041088 submission_runner.py:518] Creating experiment directory at /home/znado/dev_algo/criteo1tb_jax
I1021 20:53:42.800302 140139075041088 xla_bridge.py:345] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: 
I1021 20:53:43.548165 140139075041088 xla_bridge.py:345] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I1021 20:53:43.549550 140139075041088 xla_bridge.py:345] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I1021 20:53:44.764044 140139075041088 submission_runner.py:442] --- Tuning run 1/1 ---
I1021 20:53:44.764292 140139075041088 submission_runner.py:447] Creating tuning directory at /home/znado/dev_algo/criteo1tb_jax/trial_1
I1021 20:53:44.764459 140139075041088 logger_utils.py:39] Loading hparams from /home/znado/dev_algo/criteo1tb_jax/trial_1/hparams.json
I1021 20:53:44.873472 140139075041088 submission_runner.py:205] Initializing dataset.
I1021 20:53:44.873683 140139075041088 submission_runner.py:212] Initializing model.
2022-10-21 20:53:50.431496: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] Constant folding an instruction is taking > 1s:

  gather.2 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
2022-10-21 20:53:52.036233: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:133] The operation took 2.604949132s
Constant folding an instruction is taking > 1s:

  gather.2 (displaying the full instruction incurs a runtime overhead. Raise your logging level to 4 or above).

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
I1021 20:53:57.149762 140139075041088 submission_runner.py:215] Initializing optimizer.
I1021 20:53:59.792380 140139075041088 submission_runner.py:222] Initializing metrics bundle.
I1021 20:53:59.792682 140139075041088 submission_runner.py:239] Initializing checkpoint and logger.
I1021 20:53:59.794216 140139075041088 checkpoints.py:467] Found no checkpoint files in /home/znado/dev_algo/criteo1tb_jax/trial_1 with prefix checkpoint_
I1021 20:54:00.507258 140139075041088 submission_runner.py:260] Saving meta data to /home/znado/dev_algo/criteo1tb_jax/trial_1/meta_data_0.json
I1021 20:54:00.508363 140139075041088 submission_runner.py:263] Saving flags to /home/znado/dev_algo/criteo1tb_jax/trial_1/flags_0.json
I1021 20:54:00.540652 140139075041088 submission_runner.py:269] Starting training loop.

I1021 20:54:54.384616 140139075041088 spec.py:298] Evaluating on the training split.
I1021 20:55:02.814031 140139075041088 spec.py:310] Evaluating on the validation split.
I1021 20:56:37.957767 140139075041088 spec.py:325] Evaluating on the test split.
I1021 20:58:09.529070 140139075041088 submission_runner.py:326] Time since start: 53.84s,       Step: 1,        {'train/loss': 1.110765516757965, 'validation/loss': 1.1014636366866355, 'test/loss': 1.1020418502563654}
I1021 20:58:09.533690 139933289264896 logging_writer.py:48] [1] global_step=1, preemption_count=0, test/loss=1.102042, train/loss=1.110766, validation/loss=1.101464
I1021 20:58:11.459214 140139075041088 checkpoints.py:356] Saving checkpoint at step: 1
I1021 20:58:24.153450 140139075041088 checkpoints.py:317] Saved checkpoint at /home/znado/dev_algo/criteo1tb_jax/trial_1/checkpoint_1
I1021 20:58:24.164449 140139075041088 checkpoint_utils.py:167] Saved checkpoint to /home/znado/dev_algo/criteo1tb_jax/trial_1/checkpoint_1
2022-10-21 20:59:03.853662: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_4_bfc) ran out of memory trying to allocate 2.21GiB (rounded to 2368997376)requested by op 
2022-10-21 20:59:03.853715: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_6_bfc) ran out of memory trying to allocate 2.21GiB (rounded to 2368997376)requested by op 
2022-10-21 20:59:03.853760: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_5_bfc) ran out of memory trying to allocate 2.21GiB (rounded to 2368997376)requested by op 
2022-10-21 20:59:03.853918: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:491] ************___________*************__________************************************************______
2022-10-21 20:59:03.853998: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:491] ************___________*************__________************************************************______
2022-10-21 20:59:03.854019: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_7_bfc) ran out of memory trying to allocate 2.21GiB (rounded to 2368997376)requested by op 
2022-10-21 20:59:03.854060: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:479] Allocator (GPU_2_bfc) ran out of memory trying to allocate 2.21GiB (rounded to 2368997376)requested by op 
2022-10-21 20:59:03.854108: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:491] ************___________*************__________************************************************______
2022-10-21 20:59:03.854179: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2130] Execution of replica 4 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 2368997248 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:    4.91GiB
              constant allocation:     4.4KiB
        maybe_live_out allocation:    4.90GiB
     preallocated temp allocation:    2.21GiB
  preallocated temp fragmentation:         0B (0.00%)
                 total allocation:   12.02GiB
              total fragmentation:  613.54MiB (4.98%)
Peak buffers:
        Buffer 1:
                Size: 1.62GiB
                Entry Parameter Subshape: f32[3407872,128]
                ==========================

        Buffer 2:
                Size: 1.62GiB
                Entry Parameter Subshape: f32[3407872,128]
                ==========================

        Buffer 3:
                Size: 1.62GiB
                Entry Parameter Subshape: f32[3407872,128]
                ==========================

        Buffer 4:
                Size: 1.62GiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/add" source_file="/home/znado/env/lib/python3.7/site-packages/optax/_src/update.py" source_line=43
                XLA Label: fusion
                Shape: f32[3407872,128]
                ==========================

        Buffer 5:
                Size: 1.62GiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/add" source_file="/home/znado/env/lib/python3.7/site-packages/optax/_src/update.py" source_line=43
                XLA Label: fusion
                Shape: f32[3407872,128]
                ==========================

        Buffer 6:
                Size: 1.62GiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/add" source_file="/home/znado/env/lib/python3.7/site-packages/optax/_src/update.py" source_line=43
                XLA Label: fusion
                Shape: f32[3407872,128]
                ==========================

        Buffer 7:
                Size: 256.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/transpose(jvp(DlrmSmall))/select_n" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,1024]
                ==========================

        Buffer 8:
                Size: 256.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/transpose(jvp(DlrmSmall))/select_n" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,1024]
                ==========================

        Buffer 9:
                Size: 256.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/jvp(DlrmSmall)/jit(relu)/max" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,1024]
                ==========================

        Buffer 10:
                Size: 256.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/jvp(DlrmSmall)/jit(relu)/max" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,1024]
                ==========================

        Buffer 11:
                Size: 182.25MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/transpose(jvp(DlrmSmall))/scatter-add[update_consts=() dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0, 1, 2), scatter_dims_to_operand_dims=(0, 1, 2)) indices_are_sorted=False unique_indices=False mode=GatherScatterMode.PROMISE_IN_BOUNDS]" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=34
                XLA Label: fusion
                Shape: f32[65536,27,27]
                ==========================

        Buffer 12:
                Size: 128.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/transpose(jvp(DlrmSmall))/select_n" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,512]
                ==========================

        Buffer 13:
                Size: 128.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/jvp(DlrmSmall)/jit(relu)/max" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=121
                XLA Label: fusion
                Shape: f32[65536,512]
                ==========================

        Buffer 14:
                Size: 128.00MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/jvp(DlrmSmall)/jit(relu)/max" source_file="/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_jax/models.py" source_line=73
                XLA Label: fusion
                Shape: f32[65536,512]
                ==========================

        Buffer 15:
                Size: 126.50MiB
                Operator: op_name="pmap(pmapped_train_step)/jit(main)/transpose(jvp(DlrmSmall))/Dense_3/dot_general[dimension_numbers=(((1,), (1,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/znado/env/lib/python3.7/site-packages/flax/linen/linear.py" source_line=198
                XLA Label: custom-call
                Shape: f32[65536,506]
                ==========================
```

Pytorch stacktrace:
```
Traceback (most recent call last):
  File "submission_runner.py", line 547, in <module>
    app.run(main)
  File "/home/znado/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/znado/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 531, in main
    FLAGS.tokenizer_vocab_path)
  File "submission_runner.py", line 466, in score_submission_on_workload
    tokenizer_vocab_path)
  File "submission_runner.py", line 299, in train_once
    rng=update_rng)
  File "/home/znado/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/pytorch_submission_base.py", line 55, in update_params
    loss.backward()
  File "/home/znado/env/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/znado/env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 832.00 MiB (GPU 4; 15.78 GiB total capacity; 12.15 GiB already allocated; 474.44 MiB free; 13.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 23377 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 23378) of binary: /home/znado/env/bin/python3
```

**Comment by znado** [comment]
Both jax and pytorch seem to run fine with half the batch size (262144). Going to try looking at dtypes now.

**Comment by znado** [comment]
I tried adding `donate_argnums=(2, 3, 4)` ([docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.pmap.html)) [here](https://github.com/mlcommons/algorithmic-efficiency/blob/main/reference_algorithms/target_setting_algorithms/jax_submission_base.py#L20) similar to how we have it in init2winit and it fixed things in jax! At least it was able to get through second eval (instead of crashing shortly after the first). This is not very desirable though because having to remember this complicates things for submitters.

Also, is there any PyTorch equivalent to this? If not, we may just have to halve the batch size.

**Comment by pomonam** [comment]
I am not sure of a PyTorch equivalent to this, but it seems like the OOM happens during the backward pass. One potential solution is to set `gradient_as_bucket_view=True` in [here](https://pytorch.org/docs/master/generated/torch.nn.parallel.DistributedDataParallel.html) ([discussion](https://stackoverflow.com/questions/68949954/model-takes-twice-the-memory-footprint-with-distributed-data-parallel)) although I have not used this before.

**Comment by runame** [comment]
I also don't know about a PyTorch equivalent to this and haven't used the `gradient_as_bucket_view` argument before, but since it is said to reduce the peak memory usage it seems worth it to try it. Don't know if it can have any side-effects though, there might be a reason it's not `True` by default?

**Comment by znado** [comment]
`gradient_as_bucket_view` seems to fix it, at least it gets past 2 evals instead of OOMing shortly after the first, and I confirmed that if I toggle it back to False it OOMs. I'm going to keep it running until the max time to confirm. Thanks so much for the tip!!

Is there a reason not to set `gradient_as_bucket_view=True` for all workloads?

**Comment by pomonam** [comment]
My understanding is that `gradient_as_bucket_view=True` makes the update slightly slower (mostly my empirical observation from imagenet-resnet workload) and we cannot directly use some custom Pytorch functions such as gradient clipping since `grad.detach()` is not allowed when using this flag.

**Comment by znado** [comment]
I spoke too soon :( now Criteo OOMs about an hour into training:
```
I1024 19:53:51.048465 139926742193984 submission_runner.py:327] Time since start: 3543.52s,     Step: 1246,     {'train/loss': 0.10776905342936516, 'validation/loss': 0.12619605478505755, 'test/loss': 0.13179497585393662}
I1024 19:53:51.055636 139844034475776 logging_writer.py:48] [1246] global_step=1246, preemption_count=0, score=2675.164003, test/loss=0.131795, total_duration=3543.520157, train/loss=0.107769, validation/loss=0.126196
I1024 19:54:09.605676 139926742193984 checkpoint_utils.py:167] Saved checkpoint to /home/znado/target_setting/criteo1tb_pytorch/trial_1/checkpoint
[E ProcessGroupNCCL.cpp:737] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=15931, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1801374 milliseconds before timing out.
E1024 20:35:11.253251 140178627839808 submission_runner.py:353] Eval step 1555 error.
Traceback (most recent call last):
  File "submission_runner.py", line 322, in train_once
    global_step)
  File "/home/znado/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 307, in eval_model
    global_step=global_step)
  File "/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/workload.py", line 118, in _eval_model_on_split
    eval_batch = next(self._eval_iters[split])
  File "/home/znado/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py", line 155, in _build_input_queue
    device=DEVICE)
RuntimeError: CUDA out of memory. Tried to allocate 19.58 GiB (GPU 5; 15.78 GiB total capacity; 6.85 GiB already allocated; 7.06 GiB free; 7.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split
_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Aahh that's great to know we can't do grad clipping with it. Given all that issue, and lacking other alternatives, I think maybe it's best to revert to `gradient_as_bucket_view=False` and halve the batch size?

**Comment by runame** [comment]
I just wanted to write in the review of the PR that I don't think we should default to `gradient_as_bucket_view=True`, mainly because of what Juhan said (there are also other use cases where submissions might want to call `grad.detach()`).

**Comment by pomonam** [comment]
I agree with Runa that defaulting `gradient_as_bucket_view=True` might not be the best idea.

**Comment by znado** [comment]
I defaulted `gradient_as_bucket_view` back to `False`. We're just going to halve the batch size.

In Jax however, at the 524k batch size, I'm having issues getting the model to converge to the proper loss. The loss goes down, it just starts higher and decays slower than expected. I confirmed the model shapes are the same, and that the model variable norms at init are the same. I did fix one bug where we weren't shuffling the dataset. I'm actively working on further debugging it.

**Comment by znado** [comment]
Running the same exact batch through both our init2winit model and the GitHub model at init produce logits that are all within 5e-7 of each other, so I am convinced that the model is correct. This makes me think maybe we need to do something different with the dataset, but as far as I can tell both the internal and external datasets only applied the preprocessing as described [here](https://github.com/mlcommons/inference/blob/master/recommendation/dlrm/tf/dataloader.py#L157.) (unfortunately I don't know where the exact preprocessing code for our internal copy is, as it was generated by another team).

One diff could be how we do shuffling, if the internal copy did a global shuffle then we would need to dramatically increase our shuffle buffer size to the point that it would OOM host memory. I already have a shuffle buffer size of ~50M examples (100 training batches), and I shuffle the input files, so I would think this would provide a decent shuffle.

Another area could be the optimizer, but I've already checked the hparams and algo and it seems to be the same. I will continue digging however.

**Comment by priyakasimbeg** [comment]
To get current state of this issue, I reran Criteo Jax once with latest code on dev.
Validation loss and test loss did not hit the target.
The validation loss was within the 20 trial range of the internal target setting run.
The test loss was outside of the 20 trial range of the internal target setting run.

validation loss:
<img width="433" alt="image" src="https://github.com/mlcommons/algorithmic-efficiency/assets/12614254/71dcc413-b06d-4a82-86a3-b16ff374836a">

test loss:
<img width="385" alt="image" src="https://github.com/mlcommons/algorithmic-efficiency/assets/12614254/9e6a0bbe-f262-44d8-afdd-6491552c5a48">
