### ISSUE TITLE
WMT Pytorch loss fluctuates over time

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#227]
For the WMT Pytorch workload the loss and other metrics decrease, increase and decrease again over time. 

## Description
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/12614254/197912118-067b47e0-0f3f-44b8-9a0a-19f36c1993cc.png">

## Steps to Reproduce
On kasimbeg-6 on branch [sacrebleu](https://github.com/priyakasimbeg/algorithmic-efficiency/tree/sacrebleu) run 
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py \
    --framework=pytorch \
    --data_dir=/home/kasimbeg/tensorflow_datasets \
    --experiment_dir=/home/kasimbeg \
    --experiment_name=target_setting \
    --workload=wmt \
    --submission_path=reference_algorithms/target_setting_algorithms/pytorch_adamw.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/wmt/tuning_search_space.json > results_wmt_pytorch.txt 2>&1
```

## Source or Possible Fix

Currently investigating init, optimizers etc.

**Comment by runame** [comment]
At first glance it looks like the `update_fn` of the target setting run is not using the [correct weights](https://github.com/mlcommons/algorithmic-efficiency/blob/main/reference_algorithms/development_algorithms/wmt/wmt_pytorch/submission.py#L121-L123). The weights should be stored in `batch['weights']`. I guess, I can add this in PR #233.

**Comment by priyakasimbeg** [comment]
I think you're right Runa, testing now if that does the trick.

**Comment by pomonam** [comment]
I also found some very minor diffs in the implementation. Can push a PR soon, but it might not drastically change the results.

**Comment by runame** [comment]
@priyakasimbeg Did you already check if this solves the issue?

**Comment by priyakasimbeg** [comment]
Actually, it looks like that was the last commit on the PR before it got merged so the fix is incomplete still. Should this include the weights key? https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py#L277

**Comment by priyakasimbeg** [comment]
Could we do a similar hack to the ogbg workload where returned nans for points w weight 0 and took nanmean?

**Comment by runame** [comment]
Yes, I also thought about that, but not sure what is better. The advantage of requiring the user to take the nanmean is that submissions cannot silently fail, because the loss will just be nan, so I'm happy to implement it like this.

**Comment by runame** [comment]
I fixed it in #234, hopefully it works now.

**Comment by priyakasimbeg** [comment]
Great! thank you, I'll rerun the workload and update here

**Comment by runame** [comment]
Zack just brought up a really good point in his review of #234: if there are actually nan values in the loss, we want them to be propagated to users, so maybe we shouldn't just tell them to use nanmean, but give the general instruction to divide the summed losses by `weights.sum()` instead (and not pad the losses with nan values). This also affects the OGBG workload.

**Comment by priyakasimbeg** [comment]
Reopening for tracking, because I get a runtime error now:
```
Traceback (most recent call last):                                                                                                                                                 
  File "submission_runner.py", line 573, in <module>                                                                                                                               
    app.run(main)                                                                                                                                                                  
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                                              
    _run_main(main, args)                                                                                                                                                          
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                                        
    sys.exit(main(argv))                                                                                                                                                           
  File "submission_runner.py", line 557, in main                                                                                                                                   
    FLAGS.tokenizer_vocab_path)                                                                                                                                                    
  File "submission_runner.py", line 491, in score_submission_on_workload                                                                                                           
    tokenizer_vocab_path)                                                                                                                                                          
  File "submission_runner.py", line 310, in train_once                                                                                                                             
    rng=update_rng)                                                                                                                                                                
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/pytorch_submission_base.py", line 49, in update_params                                
    label_smoothing=label_smoothing)                                                                                                                                               
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/workload.py", line 207, in loss_fn                                                              
    label_smoothing=label_smoothing)                                                                                                                                               
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 61, in compute_weighted_cross_entropy                            
    per_example_losses = torch.where(mask, per_example_losses, 0.)                                                                                                                 
RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Long  
```

**Comment by priyakasimbeg** [comment]
Made the mask of bool type. Testing the full fix now.

**Comment by runame** [comment]
Yeah that should be the fix, I converted to boolean before but apparently messed it up again in the last refactor. Sorry about that.
