### ISSUE TITLE
WMT torch  NCCL time out error

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#247]
WMT torch crashes with NCCL time out error. 

## Description
Traceback:
```
I1103 18:06:29.961281 140411023902528 workload.py:130] Translating evaluation dataset.
I1103 18:14:11.759132 140411023902528 submission_runner.py:345] Time since start: 3.33s,        Step: 1,        {'train/accuracy': 0.0007564548963768036, 'train/loss': 10.993585429343776, 'train/bleu': 1.733641314448888e-09, 'validation/accuracy': 0.000908339253065645, 'validation/loss': 11.012303338729025, 'validation/bleu': 1.3789268837869184e-08, 'validation/num_examples': 3000, 'test/accuracy': 0.000986124646155274, 'test/loss': 10.996429648707597, 'test/bleu': 3.041362410039935e-08, 'test/num_examples': 3000}
I1103 18:14:11.763073 140352877815552 logging_writer.py:48] [1] global_step=1, preemption_count=0, test/accuracy=0.000986, test/bleu=0.000000, test/loss=10.996430, test/num_examples=3000, train/accuracy=0.000756, train/bleu=0.000000, train/loss=10.993585, validation/accuracy=0.000908, validation/bleu=0.000000, validation/loss=11.012303, validation/num_examples=3000
[E ProcessGroupNCCL.cpp:737] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605388 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605480 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605492 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605493 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605503 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605508 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=BROADCAST, Timeout(ms)=3600000) ran for 3605516 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3603516 milliseconds before timing out.
I1103 19:14:17.344123 140411023902528 checkpoint_utils.py:167] Saved checkpoint to /home/kasimbeg/target_setting/wmt_pytorch/run_3/trial_1/checkpoint
Traceback (most recent call last):
  File "submission_runner.py", line 577, in <module>
    app.run(main)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 561, in main
    FLAGS.tokenizer_vocab_path)
  File "submission_runner.py", line 499, in score_submission_on_workload
    tokenizer_vocab_path)
  File "submission_runner.py", line 304, in train_once
    data_select_rng)
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/data_selection.py", line 25, in data_selection
    return next(input_queue)
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 271, in _build_input_queue
    dist.broadcast(torch.stack(tensor_list), src=0)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=464, OpType=ALLREDUCE, Timeout(ms)=3600000) ran for 3603516 milliseconds before timing out.
```

## Steps to Reproduce
On kasimbeg-7 run:
```
orchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py \
    --framework=pytorch \
    --data_dir=/home/kasimbeg/tensorflow_datasets \
    --experiment_dir=/home/kasimbeg \
    --experiment_name=target_setting \
    --workload=wmt \
    --submission_path=reference_algorithms/target_setting_algorithms/pytorch_adamw.py \
    --tuning_search_space=reference_algorithms/target_setting_algorithms/wmt/tuning_search_space.json > results_wmt_pytorch_verify.txt 2>&1
```
## Source or Possible Fix
This has happened on other workloads like imagenet as well. Not sure what the root cause is.

**Comment by pomonam** [comment]
As @chandramouli-sastry pointed out, I think this is related to the new logging fixes. I will commit a PR soon to fix the deadlock issue.
