### ISSUE TITLE
WMT Pytorch dataset download_and_prepare breaks

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#297]
WMT dataset download and prepare breaks on fresh VM with file already exists error.

## Description
I ran the WMT pytorch workload on a fresh VM and it keeps breaking in the extract step. I tried removing the datasets folder and starting from scratch but it still gives the same error.
Traceback:
```
Extraction completed...:  67%|████████████████████████████████████████████████████████████████████████████████████████████▋                                              | 2/3 [45:06<22:33, 1353.47s/ file$
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1851/1851 [45:06<00:00,  1.46s/ MiB$
Dl Completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [45:06<00:00, 541.39s/ url$
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [42:54<00:00, 2214.98s/ file$
  File "submission_runner.py", line 591, in <module>████████████████████████████████████████████████▌                                                                      | 1/2 [41:41<00:27, 27.04s/ file$
    app.run(main)                                                                                                                                                                                           
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                                                                       
    _run_main(main, args)                                                                                                                                                                                   
  File "/home/kasimbeg/env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                                                                 
    sys.exit(main(argv))                                                                                                                                                                                    
  File "submission_runner.py", line 574, in main                                                                                                                                                            
    logging_dir_path)                                                                                                                                                                                       
  File "submission_runner.py", line 507, in score_submission_on_workload                                                                                                                                    
    tuning_dir_name)                                                                                                                                                                                        
  File "submission_runner.py", line 312, in train_once                                                                                                                                                      
    data_select_rng)                                                                                                                                                                                        
  File "/home/kasimbeg/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/data_selection.py", line 25, in data_selection                                                                 
    batch = next(input_queue)                                                                                                                                                                               
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 229, in _build_input_queue                                                                
    repeat_final_dataset)                                                                                                                                                                                   
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/workload.py", line 113, in _build_input_queue                                                                            
    repeat_final_dataset=repeat_final_dataset)                                                                                                                                                              
  File "/home/kasimbeg/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/input_pipeline.py", line 272, in get_wmt_dataset                                                                         
    dataset_builder.download_and_prepare()                                                                                                                                                                  
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 441, in download_and_prepare                                                                      
    download_config=download_config,                                                                                                                                                                        
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1114, in _download_and_prepare                                                                    
    dl_manager, **optional_pipeline_kwargs)                                                                                                                                                                 
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/translate/wmt.py", line 704, in _split_generators                                                                                
    downloaded_files = dl_manager.download_and_extract(urls_to_download)                                                                                                                                    
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 634, in download_and_extract                                                            
    return _map_promise(self._download_extract, url_or_urls)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 767, in _map_promise
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 916, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 916, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 767, in <lambda>
    res = tf.nest.map_structure(lambda p: p.get(), all_promises)  # Wait promises
  File "/home/kasimbeg/env/lib/python3.7/site-packages/promise/promise.py", line 512, in get
    return self._target_settled_value(_raise=True)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/promise/promise.py", line 516, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/promise/promise.py", line 226, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/kasimbeg/env/lib/python3.7/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow_datasets/core/download/extractor.py", line 113, in _sync_extract
    tf.io.gfile.rename(to_path_tmp, to_path)
  File "/home/kasimbeg/env/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 621, in rename_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists.

```

## Steps to Reproduce
On new VM run:
```
torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py     --framework=pytorch     --data_dir=/home/kasimbeg/tensorflow_datasets     --experiment_dir=/home/kasimbeg/experiments     --experiment_name=wmt_pytorch_verify_updated_params_trial_1     --workload=wmt     --submission_path=reference_algorithms/target_setting_algorithms/pytorch_nadamw.py     --tuning_search_space=reference_algorithms/target_setting_algorithms/wmt/tuning_search_space.json --profile
```
## Source or Possible Fix
Maybe this has to do with the pytorch multiprocess flow.

**Comment by pomonam** [comment]
Yes, there is an issue when you are downloading jax-pytorch unified input pipeline (e.g., mnist, wmt, ...) using pytorch code (on DDP). The reason is that each process simultaneously tries to download the dataset. One alternative is to download the data using the Jax code. Ultimately, We need to add `dist.barrier()` at the right place so that only one process downloads.

**Comment by priyakasimbeg** [comment]
Thanks for weighing in on this. I submitted a PR but after giving this some more thought w @znado, we've decided to not do any downloading in the input pipe. So I will delete the download step instead.

**Comment by pomonam** [comment]
Thank you for the reply. That makes sense. There are other workloads that download the datasets - we can remove them as well if we decide not to download any dataset in the input pipeline.

**Comment by znado** [comment]
https://github.com/mlcommons/algorithmic-efficiency/pull/302
