### ISSUE TITLE
Imagenet ViT broken w Incompatible shapes for broadcasting

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#331]
Imagenet ViT broken w Incompatible shapes for broadcasting

## Description

Traceback
```

Traceback (most recent call last):
  File "submission_runner.py", line 599, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 572, in main
    score = score_submission_on_workload(workload,
  File "submission_runner.py", line 507, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 320, in train_once
    optimizer_state, model_params, model_state = update_params(
  File "/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/jax_submission_base.py", line 98, in update_params
    new_optimizer_state, new_params, new_model_state, loss, grad_norm = pmapped_train_step( # pylint: disable=line-too-long
  File "/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/jax_submission_base.py", line 50, in pmapped_train_step
    (summed_loss, (n_valid_examples, new_model_state)), grad = grad_fn(
  File "/algorithmic-efficiency/reference_algorithms/target_setting_algorithms/jax_submission_base.py", line 40, in _loss_fn
    loss_dict = workload.loss_fn(
  File "/algorithmic-efficiency/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_jax/workload.py", line 179, in loss_fn
    per_example_losses *= mask_batch
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 4639, in deferring_binary_op
    return binary_op(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py", line 80, in fn
    x1, x2 = _promote_args(numpy_fn.__name__, x1, x2)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/util.py", line 344, in _promote_args
    return _promote_shapes(fun_name, *_promote_dtypes(*args))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/util.py", line 248, in _promote_shapes
    result_rank = len(lax.broadcast_shapes(*shapes))
ValueError: Incompatible shapes for broadcasting: ((1, 128), (128, 1000))
```
## Steps to Reproduce

Run reference submission for target setting for imagenet vit jax.

**Comment by sourabh2k15** [comment]
this bug seems to have been introduced due to  https://github.com/mlcommons/algorithmic-efficiency/pull/314 

essentially the mask shape is not compatible with the loss shape, speech workloads are also broken by this ... working on a fix
