### ISSUE TITLE
Imagenet Resnet pytorch broken with IndexError in eval

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#343]
Imagenet Resnet pytorch broken with IndexError in eval

## Description
Traceback:
```
Traceback (most recent call last):
  File "submission_runner.py", line 599, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 572, in main
    score = score_submission_on_workload(workload,
  File "submission_runner.py", line 507, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 351, in train_once
    latest_eval_result = workload.eval_model(global_eval_batch_size,
  File "/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 299, in eval_model
    train_metrics = self._eval_model_on_split(
  File "/algorithmic-efficiency/algorithmic_efficiency/workloads/imagenet_resnet/imagenet_pytorch/workload.py", line 275, in _eval_model_on_split
    batch = next(self._eval_iters[split])
  File "/algorithmic-efficiency/algorithmic_efficiency/data_utils.py", line 216, in cycle
    batch = next(iterator)
  File "/algorithmic-efficiency/algorithmic_efficiency/data_utils.py", line 255, in prefetched_loader
    for next_inputs, next_targets in self.dataloader:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 228, in __getitem__
    path, target = self.samples[index]
IndexError: list index out of range
```

## Steps to Reproduce

Run target setting command for imagenet resnet pytorch.

**Comment by pomonam** [comment]
I cannot reproduce this error. Could you share the command you used to run this?

**Comment by pomonam** [comment]
I suspect this might be related to data corruption.
