### ISSUE TITLE
Fancy baselines hyperparameter attribute errors

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#378]
*Provide a general description of the issue*

## Description
Traceback:
```
I0426 04:49:02.559688 140625538824000 submission_runner.py:251] After Initializing model: RAM USED (GB) 8.337543168
I0426 04:49:02.559894 140625538824000 submission_runner.py:252] Initializing optimizer.
Traceback (most recent call last):
  File "submission_runner.py", line 629, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 602, in main
    score = score_submission_on_workload(workload,
  File "submission_runner.py", line 537, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 254, in train_once
    optimizer_state = init_optimizer_state(workload,
  File "/algorithmic-efficiency/baselines/lamb/jax/submission.py", line 52, in init_optimizer_state
    b1=hyperparameters.beta1,
AttributeError: 'Hyperparameters' object has no attribute 'beta1'
```

## Steps to Reproduce
Run
```
python submission_runner.py \
        --framework=jax  \
        --workload=criteo1tb \ 
        --submission_path=baselines/lamb/jax/submission.py  \
        --tuning_search_space=baselines/lamb/tuning_search_space.json  \
        --data_dir=/home/${USER}/data \
        --num_tuning_trials=1  \
        --experiment_dir=/home/$USER/experiments  \
        --experiment_name=lamb
```

## Source or Possible Fix
The hyper parameter names in algorithmic-efficiency/baselines/lamb/tuning_search_space.json don't match the ones in the basesines/lamb/jax/submission.py.

**Comment by sourabh2k15** [comment]
jax baselines should be fixed by https://github.com/mlcommons/algorithmic-efficiency/pull/380 and https://github.com/mlcommons/algorithmic-efficiency/pull/382
