### ISSUE TITLE
DLRM debugging

### ISSUE THREAD

**Issue by kamalkraj** [mlcommons/algorithmic-efficiency#41]
I have made few changes to the original implementations and pushed them here.
https://github.com/kamalkraj/dlrm/tree/mlperf

Tested GPU: 4xNVIDIA TITAN RTX 24GB
```bash
$ nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      PHB     SYS     NV2     0-31            N/A
GPU1    PHB      X      NV1     SYS     0-31            N/A
GPU2    SYS     NV1      X      SYS     0-31            N/A
GPU3    NV2     SYS     SYS      X      0-31            N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

Main changes made
1. Updated docker file to use CUDA 11.1 and PyTorch 1.9
2. Increased no. of works to 16 for the random dataset.

I can see there is a significant increase in the GPU utilisation from ~2-3% to 20-25% (for both single and multi GPU) after increasing the num_workers.
![Screenshot 2021-10-08 at 11 22 46 PM](https://user-images.githubusercontent.com/17096858/136601246-a11179ef-6f4d-4c20-8b04-0f8f0283717f.png)

1 GPU log
```
Finished training it 100/1000 of epoch 0, 14.43 ms/it, loss 0.083825, accuracy 0.000 %
Finished training it 200/1000 of epoch 0, 13.92 ms/it, loss 0.083345, accuracy 0.000 %
Finished training it 300/1000 of epoch 0, 13.90 ms/it, loss 0.083416, accuracy 0.000 %
Finished training it 400/1000 of epoch 0, 14.15 ms/it, loss 0.083330, accuracy 0.000 %
Finished training it 500/1000 of epoch 0, 13.36 ms/it, loss 0.082989, accuracy 0.000 %
Finished training it 600/1000 of epoch 0, 15.00 ms/it, loss 0.083127, accuracy 0.000 %
Finished training it 700/1000 of epoch 0, 13.58 ms/it, loss 0.083552, accuracy 0.000 %
Finished training it 800/1000 of epoch 0, 15.09 ms/it, loss 0.083707, accuracy 0.000 %
Finished training it 900/1000 of epoch 0, 13.37 ms/it, loss 0.083474, accuracy 0.000 %
Finished training it 1000/1000 of epoch 0, 13.49 ms/it, loss 0.083342, accuracy 0.000 %
```
2 GPU log
```
Finished training it 100/1000 of epoch 0, 58.24 ms/it, loss 0.084548, accuracy 0.000 %
Finished training it 200/1000 of epoch 0, 23.10 ms/it, loss 0.083382, accuracy 0.000 %
Finished training it 300/1000 of epoch 0, 22.36 ms/it, loss 0.083459, accuracy 0.000 %
Finished training it 400/1000 of epoch 0, 24.23 ms/it, loss 0.083344, accuracy 0.000 %
Finished training it 500/1000 of epoch 0, 21.98 ms/it, loss 0.083005, accuracy 0.000 %
Finished training it 600/1000 of epoch 0, 23.14 ms/it, loss 0.083160, accuracy 0.000 %
Finished training it 700/1000 of epoch 0, 24.25 ms/it, loss 0.083573, accuracy 0.000 %
Finished training it 800/1000 of epoch 0, 24.56 ms/it, loss 0.083740, accuracy 0.000 %
Finished training it 900/1000 of epoch 0, 21.88 ms/it, loss 0.083494, accuracy 0.000 %
Finished training it 1000/1000 of epoch 0, 22.91 ms/it, loss 0.083371, accuracy 0.000 %
```
4 GPU log
```
Finished training it 100/1000 of epoch 0, 121.60 ms/it, loss 0.084548, accuracy 0.000 %
Finished training it 200/1000 of epoch 0, 27.30 ms/it, loss 0.083382, accuracy 0.000 %
Finished training it 300/1000 of epoch 0, 27.59 ms/it, loss 0.083459, accuracy 0.000 %
Finished training it 400/1000 of epoch 0, 28.07 ms/it, loss 0.083344, accuracy 0.000 %
Finished training it 500/1000 of epoch 0, 26.04 ms/it, loss 0.083005, accuracy 0.000 %
Finished training it 600/1000 of epoch 0, 28.50 ms/it, loss 0.083160, accuracy 0.000 %
Finished training it 700/1000 of epoch 0, 28.83 ms/it, loss 0.083573, accuracy 0.000 %
Finished training it 800/1000 of epoch 0, 27.76 ms/it, loss 0.083740, accuracy 0.000 %
Finished training it 900/1000 of epoch 0, 26.22 ms/it, loss 0.083494, accuracy 0.000 %
Finished training it 1000/1000 of epoch 0, 28.10 ms/it, loss 0.083371, accuracy 0.000 %
```

I am unable to download the crieto terbyte dataset due to some firewall restrictions at my end. 

@rakshithvasudev You can try increasing the num_workers for data_loader to a higher number according to your machine capacity. This should improve the training speed. Try and let me know.

**Comment by kamalkraj** [comment]
@rakshithvasudev 
Please share the excel sheet you showed yesterday in the call. I can try running with the synthetic dataset. 

!! I am unable to download the crieto terbyte dataset due to some firewall restrictions at my end.

**Comment by rakshithvasudev** [comment]
Let me try with pinning to see if that helps. As for the excel spreadsheet, I'm not sure how to upload a document here. Any suggestions?

**Comment by kamalkraj** [comment]
@rakshithvasudev 
upload to google sheets and share the link here with anyone with the link can access or add me : kamalraj97@gmail.com

**Comment by kamalkraj** [comment]
Okay.

**Comment by rakshithvasudev** [comment]
I prefer to debug the actual workload than the Criteo Kaggle workload since the size and model are not the same.  You can try and tell me if you happen to have any breakthroughs.

Just to sanity check, I tried using `num_workers` with 30 and 10, both fail exactly at the same time. That's probably why the original code set the `num_workers` to for training 0 


```
Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1000, in <module>
    for j, (X, lS_o, lS_i, T) in enumerate(train_ld):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 347, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 955, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 998, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work/dlrm_data_pytorch.py", line 284, in __getitem__
    i = index - self.day_boundary
AttributeError: 'CriteoDataset' object has no attribute 'day_boundary'
```

I need to try pinning and see if that helps by any chance.
