### ISSUE TITLE
Pytorch Conformer CUDA error

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#426]
Pytorch Conformer OOMs on GPU with adamw. 
branch: dev
test link: https://github.com/mlcommons/algorithmic-efficiency/actions/runs/5416731116/jobs/9846849204 
Expand librispeech_conformer_pytorch and then expand "Run containerized workload".

## Description
Traceback:
```
2m 48s
  File "/algorithmic-efficiency/baselines/adamw/pytorch/submission.py", line 98, in update_params
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.51 GiB (GPU 0; 15.78 GiB total capacity; 6.25 GiB already allocated; 283.44 MiB free; 13.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "submission_runner.py", line 681, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 652, in main
    score = score_submission_on_workload(
  File "submission_runner.py", line 577, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 365, in train_once
    optimizer_state, model_params, model_state = update_params(
  File "/algorithmic-efficiency/baselines/adamw/pytorch/submission.py", line 98, in update_params
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.51 GiB (GPU 3; 15.78 GiB total capacity; 6.25 GiB already allocated; 259.44 MiB free; 13.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "submission_runner.py", line 681, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 652, in main
    score = score_submission_on_workload(
  File "submission_runner.py", line 577, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 365, in train_once
    optimizer_state, model_params, model_state = update_params(
  File "/algorithmic-efficiency/baselines/adamw/pytorch/submission.py", line 98, in update_params
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.51 GiB (GPU 7; 15.78 GiB total capacity; 6.25 GiB already allocated; 257.44 MiB free; 13.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Steps to Reproduce

On kasimbeg-3:
```
docker pull us-central1-docker.pkg.dev/training-algorithms-external/mlcommons-docker-repo/algoperf_jax_dev 
```
```
docker run  -v $HOME/data/:/data/ -v $HOME/experiment_runs/:/experiment_runs -v $HOME/experiment_runs/logs:/logs --gpus all --ipc=host us-central1-docker.pkg.dev/training-algorithms-external/mlcommons-docker-repo/algoperf_pytorch_dev -d librispeech -f pytorch -s baselines/adamw/pytorch/submission.py -w librispeech_conformer -t baselines/adamw/tuning_search_space.json -e test_today/adamw -m 10 -c False -o True -r false
```

**Comment by sourabh2k15** [comment]
So it seems like 3 training steps and 1 eval ran successfully and then it OOMed on backward pass in train step ... I remember when Chandramouli initially ported conformer to pytorch it was OOMs so we had to add this line to prevent OOM : 

https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/librispeech_conformer/librispeech_pytorch/workload.py#L51

trying to see if behaviour for this flag changed somehow in torch 2.0 or with torch.compile

**Comment by priyakasimbeg** [comment]
As a side note,  I ran with --torch_compile flag which caused the submission_runner  to crash with `CUDA error:misaligned address`. 
Full trace back in  https://github.com/mlcommons/algorithmic-efficiency/actions/runs/5534559953/jobs/10099946892 under librispeech_conformer_pytorch > Run containerized workload.

**Comment by sourabh2k15** [comment]
should be fixed by https://github.com/mlcommons/algorithmic-efficiency/pull/442
