### ISSUE TITLE
RuntimeError: shape '[213568]' is invalid for input of size 262144 on criteo1tb

### ISSUE THREAD

**Issue by ezyang** [mlcommons/algorithmic-efficiency#475]
I'm running criteo1tb with the PyTorch baseline on a single GPU

```
$ CUDA_VISIBLE_DEVICES=5 python submission_runner.py  --framework=pytorch     --workload=criteo1tb    --data_dir=$HOME/data/criteo  --experiment_dir=$HOME/experiments     --experiment_name=my_first_experiment     --submission_path=reference_algorithms/development_algorithms/criteo1tb/criteo1tb_pytorch/submission.py     --tuning_search_space=reference_algorithms/development_algorithms/criteo1tb/tuning_search_space.json --overwrite --torch_compile=0
```

with a reduced set of the input data

```
diff --git a/algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py b/algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py
index 17877d06..2f63adee 100644
--- a/algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py
+++ b/algorithmic_efficiency/workloads/criteo1tb/input_pipeline.py
@@ -93,8 +93,9 @@ def get_criteo1tb_dataset(split: str,
                           repeat_final_dataset: bool = False):
   """Get the Criteo 1TB dataset for a given split."""
   num_test_files = _NUM_DAY_23_FILES // 2 + 1
-  if split in ['train', 'eval_train']:
-    file_paths = [os.path.join(data_dir, f'day_{d}_*') for d in range(0, 23)]
+  if split in ['train', 'eval_train'] or True:
+    #file_paths = [os.path.join(data_dir, f'day_{d}_*') for d in range(0, 23)]
+    file_paths = [os.path.join(data_dir, f'day_0_000.csv')]
   elif split == 'validation':
     # Assumes files are of the format day_23_04.
     file_paths = [
```

but it seems to fail (even without torch.compile) with

```
I0810 06:58:29.672421 139861006926848 submission_runner.py:259] Starting training loop.
I0810 06:58:41.968837 139861006926848 spec.py:320] Evaluating on the training split.
Traceback (most recent call last):
  File "/data/users/ezyang/a/algorithmic-efficiency/submission_runner.py", line 604, in <module>
    app.run(main)
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/site-packages/absl_py-1.4.0-py3.10.egg/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ezyang/local/a/pytorch-env/lib/python3.10/site-packages/absl_py-1.4.0-py3.10.egg/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/users/ezyang/a/algorithmic-efficiency/submission_runner.py", line 575, in main
    score = score_submission_on_workload(
  File "/data/users/ezyang/a/algorithmic-efficiency/submission_runner.py", line 500, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "/data/users/ezyang/a/algorithmic-efficiency/submission_runner.py", line 312, in train_once
    latest_eval_result = workload.eval_model(global_eval_batch_size,
  File "/data/users/ezyang/a/algorithmic-efficiency/algorithmic_efficiency/spec.py", line 321, in eval_model
    train_metrics = self._eval_model_on_split(
  File "/data/users/ezyang/a/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/workload.py", line 133, in _eval_model_on_split
    loss += self._eval_batch(params, eval_batch)
  File "/data/users/ezyang/a/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py", line 233, in _eval_batch
    summed_loss = self.loss_fn(
  File "/data/users/ezyang/a/algorithmic-efficiency/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py", line 57, in loss_fn
    mask_batch = torch.reshape(mask_batch, (batch_size,))
RuntimeError: shape '[213568]' is invalid for input of size 262144
```

**Comment by msaroufim** [comment]
Try dividing this by 8 https://github.com/mlcommons/algorithmic-efficiency/blob/main/algorithmic_efficiency/workloads/criteo1tb/criteo1tb_pytorch/workload.py#L25

Their batch sizes assume 8 GPUs

**Comment by ezyang** [comment]
Dividing it by 8 doesn't work:

```
RuntimeError: shape '[16960]' is invalid for input of size 32768
```

but it does seem plausible that the single gpu math is wrong. need to read some more...

**Comment by ezyang** [comment]
I tried running with DDP and 8 GPUs and got `RuntimeError: shape '[26696]' is invalid for input of size 32768`. So maybe the problem is just hard-coded training set size that doesn't work with the smaller dataset.

**Comment by ezyang** [comment]
(That was the problem)

**Comment by msaroufim** [comment]
So I tilted a bit trying to find the right configuration to make something run on a single V100 WMT model, it'd be really nice for local debugging to have parameters divided depending on how many GPUs are available

**Comment by priyakasimbeg** [comment]
Will add clarifying instructions in README FAQs on gotchas when running with single GPU.
