### ISSUE TITLE
ViT Torch compile: BackendCompilerFailed Cannot call sizes() on tensor with symbolic sizes strides on torch nightly

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#496]
Torch compile back end compiler raises a RuntimeError on the PyTorch ViT workload with torch nightly version torch.dev08202023.

## Description
The ViT workload compiles on the stable version 2.0.1 but raises a Runtime error on torch.dev08202023.

Traceback:
```
Traceback (most recent call last):
2023-08-22T00:39:23.2881489Z   File "/usr/local/lib/python3.8/dist-packages/torch/fx/graph_module.py", line 274, in __call__
2023-08-22T00:39:23.2882332Z     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
2023-08-22T00:39:23.2884055Z   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-08-22T00:39:23.2885032Z     return self._call_impl(*args, **kwargs)
2023-08-22T00:39:23.2885588Z   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-08-22T00:39:23.2885995Z     return forward_call(*args, **kwargs)
2023-08-22T00:39:23.2886318Z   File "<eval_with_key>.1130", line 54, in forward
2023-08-22T00:39:23.2886739Z     matmul = torch.matmul(permute_2, transpose_1);  permute_2 = transpose_1 = None
2023-08-22T00:39:23.2887195Z RuntimeError: Cannot call sizes() on tensor with symbolic sizes/strides
2023-08-22T00:39:23.2887443Z 
2023-08-22T00:39:23.2888076Z Call using an FX-traced Module, line 54 of the traced Module's generated forward function:
2023-08-22T00:39:23.2888624Z     transpose_1 = permute.transpose(-1, -2);  permute = None
2023-08-22T00:39:23.2889057Z     matmul = torch.matmul(permute_2, transpose_1);  permute_2 = transpose_1 = None
2023-08-22T00:39:23.2889302Z 
2023-08-22T00:39:23.2889557Z ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
2023-08-22T00:39:23.2889877Z     truediv_2 = matmul / 8.0;  matmul = None
2023-08-22T00:39:23.2890068Z 
2023-08-22T00:39:23.2890393Z     softmax = torch.nn.functional.softmax(truediv_2, dim = -1);  truediv_2 = None
```

https://gist.github.com/priyakasimbeg/5e12fddbc5960a11feec3e1728ccec29#file-gistfile1-txt

## Steps to Reproduce
pytorch version: torch.dev08202023

torchrun --redirects 1:0,2:0,3:0,4:0,5:0,6:0,7:0 --standalone --nnodes=1 --nproc_per_node=8 submission_runner.py --framework=pytorch --workload=imagenet_vit --submission_path=baselines/adamw/pytorch/submission.py --tuning_search_space=baselines/adamw/tuning_search_space.json --data_dir=/data/imagenet/pytorch --num_tuning_trials=1 --experiment_dir=/experiment_runs --experiment_name=tests/regression_tests/adamw --overwrite=True --save_checkpoints=False --max_global_steps=10 --imagenet_v2_data_dir=/data/imagenet/pytorch --torch_compile=true 2>&1 | tee -a /logs/imagenet_vit_pytorch_08-22-2023-00-35-20.log

## Source or Possible Fix
Not sure what broke but the ViT workload runs without errors on on the torch stable version 2.0.1.

**Comment by msaroufim** [comment]
I've also been seeing dynamic shape errors pop up, I'm at an offsite today but I'd start with disabling these and seeing if it makes a difference https://github.com/pytorch/pytorch/blob/main/torch/_dynamo/config.py#L67-L78

Maybe @ezyang has some insight on how to debug this

**Comment by priyakasimbeg** [comment]
Disabling those flags eliminates that error message. 
Tested on branch vit_torch_nightly_debugging.

Is disabling the flags for dynamic shapes a good medium-term solution?

**Comment by msaroufim** [comment]
Well once you disable them then it's likely you'll get some recompilation so you're trading off something that works vs something that is fast. The better medium term solution is figuring out what shapes are dynamic and making them static

**Comment by ezyang** [comment]
The error here, btw, is the kind of error that happens if you don't have the python dispatcher turned on when we are decomposing matmul. Except that doesn't make any sense because I'm pretty sure we rewrote matmul not to do this anyway...

**Comment by priyakasimbeg** [comment]
Won't fix.
